version: "3"

services:
  # server:
  #   container_name: server
  #   build: .
  #   ports:
  #     - "3000:3000"
    
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123